### ISSUE TITLE
¿Could you add more locations?

### ISSUE THREAD

**Issue by deenz-dev** [BManZ07/bm_extramenu#1]
It would be interesting to be able to add more locations, i been trying but its giving me some errors, so i would appreciate if you can do it! ty <3

**Comment by BManZ07** [comment]
@deenz-dev Hi, this will be released along with a major clean up and rework of the code later today.

**Comment by BManZ07** [comment]
@deenz-dev Latest commit has the up to date changes which allow for multiple locations. Let me know if you have any further issues.

**Comment by deenz-dev** [comment]
Thank you so much! Works prefectly! thanks!
